database:
  host: 49.52.10.156
  port: 3306
  user: xzy 
  passwd: 
  db: miv_top
  table: resource_tb
server:
  ip: 49.52.10.xx
  member:
    - xzy
    - wjh
    - wtt
email:
  title: GPU Situation
  host_server: 'smtp.qq.com'
  sender: 926214756@qq.com
  author_code: lgkmzvgcovfgbfii
  table_header: 
    - Name
    - Server_name
    - GPUs
    - Time
    - Running_time
  html: """
      <html>
      <head>
      <style> 
        table, th, td {{ border: 1px solid black; border-collapse: collapse; }}
        th, td {{ padding: 5px; }}
      </style>
      </head>
      <body><p>Hello, Friend.</p>
      <p>Here is your data:</p>
      {}
      <p>Regards,</p>
      <p>Me</p>
      </body></html>
      """
  text: """
      Hello, Friend.

      Here is your data:

      {}

      Regards,

      Me"""

  receiver:
    - xzy: 936214756@qq.com
    - zhk: 1140519779@qq.com
    - jzw: 51205901097@stu.ecnu.edu.cn
    - yqs: 1729609500@qq.com
    - zyj: 627039309@qq.com
    - hfy: 1027482997@qq.com
    - lzy: 563909094@qq.com
    - wx: 51205901084@stu.ecnu.edu.cn
    - dqy: 649310204@qq.com
log:
  path: '../GPU_usage.log'